### ISSUE TITLE
Error in `cor_test_bayesian` due to bug in invgamma library

### ISSUE THREAD

**Issue by C-J-Cundy** [philipboeken/PTTests#4]
Hi, there is currently a bug in the implementation of `cor_test_bayesian`. 
On line 38 we have `invgamma::dinvgamma(g, shape = .5, scale = n / 2))`.
Unfortunately, due to a bug in invgamma https://github.com/dkahle/invgamma/issues/1, this actually computes the inverse gamma density for *rate* n/2, instead of *scale*. 

This resulted in a situation where `cor_test_bayesian` always resulted in a Bayes factor of 1, even for large amounts of completely uncorrelated data.

**Comment by philipboeken** [comment]
Hi, thanks for the heads-up. I've committed a fix in the master branch.

**Comment by dkahle** [comment]
Thought I'd tag this response here for future readers. TL;DR: the parameters in **invgamma** refer to the parameters of the pre-transformed distribution functions, e.g. `dgamma()`. 

[Fuller explanation here.](https://github.com/dkahle/invgamma/issues/1#issuecomment-1382433595) Sorry for the confusion!
